spring:
  config:
    activate:
      on-profile: local-cluster
  datasource:
    url: ${MANAO_DB_URL:jdbc:mysql://127.0.0.1:3306/manao_poc4}
    username: ${MANAO_DB_USERNAME:manao}
    password: ${MANAO_DB_PASSWORD:}
manao:
  poc4:
    backend:
      profile: local-cluster
      kubernetes:
        master-url: https://127.0.0.1:6443
