export type ApiErrorCode =
  | 'UNAUTHENTICATED'
  | 'FORBIDDEN'
  | 'PROJECT_LIMIT_REACHED'
  | 'VALIDATION_ERROR'
  | 'INTERNAL_ERROR'
  | 'INVALID_PATH'
  | 'FILE_TOO_LARGE'
  | 'BINARY_FILE'
  | 'PROJECT_LOCKED'
  | 'WORKSPACE_REVISION_CONFLICT'
  | 'ENTRY_ALREADY_EXISTS'
  | 'ENTRY_NOT_FOUND'
  | 'DIRECTORY_NOT_EMPTY'
  | 'RUN_ALREADY_ACTIVE'
  | 'RUN_STATE_CONFLICT'
  | 'RUN_NOT_FOUND'
  | 'LOG_TICKET_NOT_AVAILABLE'
  | 'TERMINAL_NOT_AVAILABLE'
  | 'TERMINAL_SESSION_ALREADY_ACTIVE'
  | 'TERMINAL_TICKET_NOT_AVAILABLE'
  | 'PROJECT_CREATING'
  | 'PROJECT_BUSY'
  | 'PROJECT_CLEANUP_INCOMPLETE'
  | 'PUBLIC_PORT_RESERVED'
  | 'PUBLIC_PORT_IN_USE'
  | 'PUBLIC_PORT_PREFLIGHT_UNAVAILABLE'
  | 'CREATE_REQUEST_MISMATCH'
  | 'DEPENDENCY_NOT_READY'
  | 'DEPENDENCY_RECOVERY_REQUIRED'
  | 'PUBLIC_ENDPOINT_UNCONFIRMED';

export type ApiErrorBody = {
  code: ApiErrorCode;
  message: string;
  traceId: string;
};
